# Generated by Django 4.0.4 on 2022-05-19 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email']},
        ),
    ]
