# Generated by Django 4.0.4 on 2022-05-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[(1, 'admin'), (2, 'client'), (3, 'company')], max_length=10, null=True),
        ),
    ]
