# Generated by Django 4.0.4 on 2022-05-22 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_role'),
        ('request', '0003_alter_request_client_alter_request_company_and_more'),
        ('notification', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='user.company'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='request.request'),
        ),
    ]
