# Generated by Django 4.0.4 on 2022-05-19 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_notification_type_of_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['created_at']},
        ),
    ]
