# Generated by Django 4.0.4 on 2022-05-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
