# Generated by Django 4.0.4 on 2022-05-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_client_alter_review_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='commentslug',
            field=models.SlugField(null=True),
        ),
    ]
