# Generated by Django 4.0.4 on 2022-05-09 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_of_request', models.CharField(max_length=255)),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.client')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.request_status')),
            ],
        ),
    ]
