# Generated by Django 4.0.4 on 2022-05-27 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_alter_request_client_alter_request_company_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request_status',
            new_name='RequestStatus',
        ),
        migrations.AlterModelOptions(
            name='requeststatus',
            options={'ordering': ['name'], 'verbose_name_plural': 'requeststatuses'},
        ),
    ]
