# Generated by Django 4.0.4 on 2022-05-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_rename_request_status_requeststatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
