# Generated by Django 4.0.4 on 2022-05-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_alter_request_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['created_at']},
        ),
    ]
