# Generated by Django 4.0.4 on 2022-05-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_alter_request_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request_status',
            options={'ordering': ['name']},
        ),
    ]
