# Generated by Django 4.0.4 on 2022-05-19 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['created_at']},
        ),
    ]
