# Generated by Django 4.0.4 on 2022-05-12 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost_of_service',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
